### ISSUE TITLE
Any api for cancelling service calls?

### ISSUE THREAD

**Issue by Hardenn** [RedMadRobot/service-autograph#1]
Previous service generator didn't have API for cancelling service calls. 

Why do we need it? 

For example, app caches data from server. When app sends request, user logs out (server not answered yet). We can't cancel request, so it comes back and service saves data. After that user logs in and sees cached data from previous session.

**Comment by taflanidi** [comment]
Hi @Hardenn 
Thanks for your question.

Well, first of all, it is nice and responsible to provide a high-level access to the existing low-level calls. `NSURLSession` has mechanisms of cancelling its running tasks, `Alamofire` and `HTTPTransport` subsequently expose these mechanisms to the end user, thus current service generator should support this feature, too.

You are not obligated to cover all the APIs when it comes to building a custom in-house utility library, but we are talking about an open source project here, and even if you can't come up with a decent example of usage of some particular call, it's not a good idea to restrict your user from using it.

Regarding your example, I'd like to indicate it's quite unnatural for any frontend to continue an authenticated session after user logout. In fact, this is a root cause for the most of the spoofing attacks, and you are out of luck in case your app operates over any kind of valuable information. 

The best way to defend the data is getting rid of it. Thus, client apps are supposed to erase in-session information after the logout by default. All other strategies assume trade-offs, and most often include YAGNI violations. I'm talking about trade-offs like making a decision about some particular array of information is safe enough to keep for the price of not making an HTTP request; plus you've got to add some logic distinguishing data between user accounts. Instead, after the logout you could have simply cancelled the HTTP call, and could have casted a single `database.deleteAll()`.

Like, instead of treating your cached information with some additional care, you just forget it even existed in the first place. No flow of control means less bugs.

Also, would **you** trust an application that saves your info after you clearly pressed the "Logout" button and then eventually came back? I'd rather not.

Okay, last but not least, there's a few tips about cancelling HTTP calls you should consider using in your app.

First, cancel when application resigns active. You never do this, yet you should. 
iOS allows execution for 180 additional seconds (or even more) after your application did enter background (surprise!), and processing between your app and current app actually overlaps. So be a good citizen.

Second, cancel while on EDGE. Again, you never do this, yet you should.
Fancy queue of outgoing HTTP calls is fun and games, but you should keep only one call alive while the Internet connection is not so good.

Third, it is a good thing to omit callbacks when it comes to chain HTTP calls (calls that depend on each other). Using a direct flow of control instead of callbacks is an `HTTPTransport` feature, yet a single large service call is a bad neighbour for other concurrent HTTP calls. Imagine you leave the user to navigate the app while your large main screen is being loaded. In this case, it might be a good idea to cancel all the collateral calls. 

For instance, when your app has a heavy main screen and a few other tabs, and the user starts to spam-click secondary tabs triggering the underlying HTTP calls. Without interrupting the main screen loading, you simply cancel all the unnecessary calls, leaving alive only the main screen call and current tab call.

Also, cancelling might be handy for the semi-offline synchronisation management. Like, when your app  operates over some local data, and eventually has to upload all the changes at the end of the day.
Remember, you backend receives a proper "close connection" signal when you cancel, too.

Should you have any clarifying questions, please go ahead and ask them here.

**Comment by ton252** [comment]
As I understood, the question was: "How we can cancel the service call?".

All we need is to define a return type `CancelableServiceCall` in our service protocol and service generator will do all for us. CancelableServiceCall have a method `cancel()`.

How it works inside:
The `cancel()` method of `CancelableServiceCall` object is just a wrapper around  of `HTTPCall` `cancel()`.
This dependency was injected by code generator like this:

```
class CancelableServiceCall<Payload> {
   ...
   // Closure that will be set in service method
    var cancelClosure: Cancel?
    
   // Method that will call this closure
    func cancel() -> Bool {
        defer {
            cancelClosure?()
        }
        return nil != cancelClosure
    }
   ...
}

class ExampleServiceGen {
  func exampleMethod() -> CancelableServiceCall<Void> {
       return createCancelableCall() { (this: CancelableServiceCall<Void>, callback: @escaping (ServiceCallResult<Void>) -> ()) in
       ...
       let httpCall: HTTPCall = self.transport.send(request: request) { (result: HTTPTransport.Result) in
                switch result {
                    case .success(_):
                        let payload: Void = ()
                        callback(ServiceCallResult.success(payload: payload))
                    case .failure(let error):
                        callback(ServiceCallResult.failure(error: error))
                }
            }
            // Set the cancelClosure
            this.cancelClosure = {
                httpCall.cancel()
            }
       ...
  }
}
```

**Comment by Hardenn** [comment]
@taflanidi First of all, thanks for such detailed and complete explanation, especially interesting info about best practices doing network requests. 

My question was (as @ton252 mentioned) is there any possibility to cancel service call, and he provided straight answer that there is. So question is closed 👍
